

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."UserHasQuestStatus" AS ENUM (
    'incomplete',
    'completed',
    'claimed'
);


ALTER TYPE "public"."UserHasQuestStatus" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."items" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "icon" "text" NOT NULL,
    "category" "text" NOT NULL,
    "buyPrice" numeric,
    "sellPrice" numeric,
    "requiredLevel" numeric DEFAULT '1'::numeric NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "slug" "text"
);


ALTER TABLE "public"."items" OWNER TO "postgres";


ALTER TABLE "public"."items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."quests" (
    "id" bigint NOT NULL,
    "category" "text" NOT NULL,
    "itemId" bigint,
    "amount" numeric,
    "xp" numeric,
    "coins" numeric,
    "startAt" timestamp with time zone NOT NULL,
    "endAt" timestamp with time zone,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" "text"
);


ALTER TABLE "public"."quests" OWNER TO "postgres";


ALTER TABLE "public"."quests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."quests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."referrals" (
    "id" bigint NOT NULL,
    "fid" numeric NOT NULL,
    "referredFid" numeric NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."referrals" OWNER TO "postgres";


ALTER TABLE "public"."referrals" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."referrals_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."requests" (
    "id" bigint NOT NULL,
    "fid" numeric NOT NULL,
    "itemId" bigint,
    "quantity" numeric,
    "filledQuantity" numeric DEFAULT '0'::numeric NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."requests" OWNER TO "postgres";


ALTER TABLE "public"."requests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."requests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_grid_cells" (
    "fid" numeric NOT NULL,
    "x" bigint NOT NULL,
    "y" bigint NOT NULL,
    "cropType" "text",
    "plantedAt" timestamp with time zone,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "isReadyToHarvest" boolean DEFAULT false NOT NULL,
    "yieldBoost" numeric,
    "speedBoostedAt" timestamp with time zone,
    "harvestAt" timestamp with time zone
);


ALTER TABLE "public"."user_grid_cells" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_has_items" (
    "userFid" numeric NOT NULL,
    "itemId" bigint NOT NULL,
    "quantity" numeric DEFAULT '1'::numeric NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."user_has_items" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_has_quests" (
    "id" bigint NOT NULL,
    "fid" numeric NOT NULL,
    "questId" bigint NOT NULL,
    "completedAt" timestamp with time zone,
    "createdAt" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "progress" numeric DEFAULT '0'::numeric NOT NULL,
    "status" "text" DEFAULT 'incomplete'::"text" NOT NULL
);


ALTER TABLE "public"."user_has_quests" OWNER TO "postgres";


ALTER TABLE "public"."user_has_quests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_has_quests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_notification" (
    "id" bigint NOT NULL,
    "fid" numeric NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "category" character varying NOT NULL
);


ALTER TABLE "public"."user_notification" OWNER TO "postgres";


COMMENT ON TABLE "public"."user_notification" IS 'Table to manage the user notifications';



ALTER TABLE "public"."user_notification" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_notification_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "fid" numeric NOT NULL,
    "username" "text" NOT NULL,
    "displayName" "text" NOT NULL,
    "avatarUrl" "text",
    "walletAddress" "text",
    "xp" numeric DEFAULT '0'::numeric NOT NULL,
    "coins" numeric DEFAULT '0'::numeric NOT NULL,
    "expansions" numeric DEFAULT '0'::numeric NOT NULL,
    "notificationDetails" "text",
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."quests"
    ADD CONSTRAINT "quests_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."referrals"
    ADD CONSTRAINT "referrals_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."requests"
    ADD CONSTRAINT "requests_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_grid_cells"
    ADD CONSTRAINT "user_grid_cells_pkey" PRIMARY KEY ("fid", "x", "y");



ALTER TABLE ONLY "public"."user_has_items"
    ADD CONSTRAINT "user_has_items_pkey" PRIMARY KEY ("userFid", "itemId");



ALTER TABLE ONLY "public"."user_has_quests"
    ADD CONSTRAINT "user_has_quests_fid_quest_id_key" UNIQUE ("fid", "questId");



ALTER TABLE ONLY "public"."user_has_quests"
    ADD CONSTRAINT "user_has_quests_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_notification"
    ADD CONSTRAINT "user_notification_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("fid");



CREATE INDEX "idx_user_has_quests_fid" ON "public"."user_has_quests" USING "btree" ("fid");



CREATE INDEX "idx_user_has_quests_quest_id" ON "public"."user_has_quests" USING "btree" ("questId");



CREATE INDEX "user_has_quests_fid_idx" ON "public"."user_has_quests" USING "btree" ("fid");



CREATE INDEX "user_has_quests_quest_id_idx" ON "public"."user_has_quests" USING "btree" ("questId");



ALTER TABLE ONLY "public"."user_grid_cells"
    ADD CONSTRAINT "player_grid_cells_fid_fkey" FOREIGN KEY ("fid") REFERENCES "public"."users"("fid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."quests"
    ADD CONSTRAINT "quests_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "public"."items"("id");



ALTER TABLE ONLY "public"."referrals"
    ADD CONSTRAINT "referrals_fid_fkey" FOREIGN KEY ("fid") REFERENCES "public"."users"("fid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."requests"
    ADD CONSTRAINT "requests_fid_fkey" FOREIGN KEY ("fid") REFERENCES "public"."users"("fid");



ALTER TABLE ONLY "public"."requests"
    ADD CONSTRAINT "requests_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "public"."items"("id");



ALTER TABLE ONLY "public"."user_has_items"
    ADD CONSTRAINT "user_has_items_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "public"."items"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_has_items"
    ADD CONSTRAINT "user_has_items_userFid_fkey" FOREIGN KEY ("userFid") REFERENCES "public"."users"("fid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_has_quests"
    ADD CONSTRAINT "user_has_quests_fid_fkey" FOREIGN KEY ("fid") REFERENCES "public"."users"("fid");



ALTER TABLE ONLY "public"."user_has_quests"
    ADD CONSTRAINT "user_has_quests_questId_fkey" FOREIGN KEY ("questId") REFERENCES "public"."quests"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_notification"
    ADD CONSTRAINT "user_notification_fid_fkey" FOREIGN KEY ("fid") REFERENCES "public"."users"("fid") ON DELETE CASCADE;



ALTER TABLE "public"."items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."quests" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."referrals" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."requests" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_grid_cells" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_has_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_has_quests" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_notification" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



































































































































































































GRANT ALL ON TABLE "public"."items" TO "anon";
GRANT ALL ON TABLE "public"."items" TO "authenticated";
GRANT ALL ON TABLE "public"."items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."quests" TO "anon";
GRANT ALL ON TABLE "public"."quests" TO "authenticated";
GRANT ALL ON TABLE "public"."quests" TO "service_role";



GRANT ALL ON SEQUENCE "public"."quests_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."quests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."quests_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."referrals" TO "anon";
GRANT ALL ON TABLE "public"."referrals" TO "authenticated";
GRANT ALL ON TABLE "public"."referrals" TO "service_role";



GRANT ALL ON SEQUENCE "public"."referrals_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."referrals_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."referrals_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."requests" TO "anon";
GRANT ALL ON TABLE "public"."requests" TO "authenticated";
GRANT ALL ON TABLE "public"."requests" TO "service_role";



GRANT ALL ON SEQUENCE "public"."requests_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."requests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."requests_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_grid_cells" TO "anon";
GRANT ALL ON TABLE "public"."user_grid_cells" TO "authenticated";
GRANT ALL ON TABLE "public"."user_grid_cells" TO "service_role";



GRANT ALL ON TABLE "public"."user_has_items" TO "anon";
GRANT ALL ON TABLE "public"."user_has_items" TO "authenticated";
GRANT ALL ON TABLE "public"."user_has_items" TO "service_role";



GRANT ALL ON TABLE "public"."user_has_quests" TO "anon";
GRANT ALL ON TABLE "public"."user_has_quests" TO "authenticated";
GRANT ALL ON TABLE "public"."user_has_quests" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_has_quests_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_has_quests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_has_quests_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_notification" TO "anon";
GRANT ALL ON TABLE "public"."user_notification" TO "authenticated";
GRANT ALL ON TABLE "public"."user_notification" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_notification_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_notification_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_notification_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
